import { User, KPI, Alert, SystemConfig } from "./types";

// ─────────────────────────────────────────────
// USERS — 28 total (1 ADMIN, 1 VP, 2 MGR, 4 AM, 20 STF)
// ─────────────────────────────────────────────
export const mockUsers: User[] = [
    // Level 0 — Administrator
    {
        id: "ADM001",
        name: "System Administrator",
        email: "admin@company.id",
        password: "password123", // Using simple password for testing
        level: 0,
        reporting_to_id: null,
        department: "IT Infrastructure & Security",
        position: "Administrator",
        status: "active",
    },

    // Level 1 — VP
    {
        id: "VP001",
        name: "Ahmad Santoso",
        email: "vp001@company.id",
        password: "password",
        level: 1,
        reporting_to_id: null,
        department: "Direktorat Utama",
        position: "Vice President",
    },

    // Level 2 — Manager
    {
        id: "MGR001",
        name: "Budi Setiawan",
        email: "mgr001@company.id",
        password: "password",
        level: 2,
        reporting_to_id: "VP001",
        department: "Divisi Operasional",
        position: "Manager Operasional",
    },
    {
        id: "MGR002",
        name: "Citra Dewi",
        email: "mgr002@company.id",
        password: "password",
        level: 2,
        reporting_to_id: "VP001",
        department: "Divisi Teknologi",
        position: "Manager Teknologi",
    },

    // Level 3 — Assistant Manager
    {
        id: "AM001",
        name: "Dian Pratama",
        email: "am001@company.id",
        password: "password",
        level: 3,
        reporting_to_id: "MGR001",
        department: "Tim Layanan Lapangan",
        position: "Asst. Manager Layanan",
    },
    {
        id: "AM002",
        name: "Eko Raharjo",
        email: "am002@company.id",
        password: "password",
        level: 3,
        reporting_to_id: "MGR001",
        department: "Tim Distribusi",
        position: "Asst. Manager Distribusi",
    },
    {
        id: "AM003",
        name: "Fitri Handayani",
        email: "am003@company.id",
        password: "password",
        level: 3,
        reporting_to_id: "MGR002",
        department: "Tim Infrastruktur IT",
        position: "Asst. Manager Infrastruktur",
    },
    {
        id: "AM004",
        name: "Gunawan Susilo",
        email: "am004@company.id",
        password: "password",
        level: 3,
        reporting_to_id: "MGR002",
        department: "Tim Pengembangan Sistem",
        position: "Asst. Manager Pengembangan",
    },

    // Level 4 — Staff (20 users)
    // Under MGR001 directly
    {
        id: "STF001",
        name: "Hendra Wibowo",
        email: "stf001@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "MGR001",
        department: "Divisi Operasional",
        position: "Staff Senior Operasional",
    },
    {
        id: "STF002",
        name: "Indah Kusuma",
        email: "stf002@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "MGR001",
        department: "Divisi Operasional",
        position: "Staff Administrasi",
    },

    // Under AM001
    {
        id: "STF003",
        name: "Joko Widodo",
        email: "stf003@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM001",
        department: "Tim Layanan Lapangan",
        position: "Teknisi Lapangan",
    },
    {
        id: "STF004",
        name: "Kartini Wahyuni",
        email: "stf004@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM001",
        department: "Tim Layanan Lapangan",
        position: "Teknisi Lapangan",
    },
    {
        id: "STF005",
        name: "Lutfi Hakim",
        email: "stf005@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM001",
        department: "Tim Layanan Lapangan",
        position: "Koordinator Layanan",
    },
    {
        id: "STF006",
        name: "Maya Sari",
        email: "stf006@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM001",
        department: "Tim Layanan Lapangan",
        position: "Staff Lapangan",
    },

    // Under AM002
    {
        id: "STF007",
        name: "Nugroho Adi",
        email: "stf007@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM002",
        department: "Tim Distribusi",
        position: "Koordinator Distribusi",
    },
    {
        id: "STF008",
        name: "Oktaviani Putri",
        email: "stf008@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM002",
        department: "Tim Distribusi",
        position: "Staff Distribusi",
    },
    {
        id: "STF009",
        name: "Pandu Kusuma",
        email: "stf009@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM002",
        department: "Tim Distribusi",
        position: "Staff Distribusi",
    },
    {
        id: "STF010",
        name: "Qomariyah Sari",
        email: "stf010@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM002",
        department: "Tim Distribusi",
        position: "Admin Distribusi",
    },

    // Under MGR002 directly
    {
        id: "STF011",
        name: "Rizky Firmansyah",
        email: "stf011@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "MGR002",
        department: "Divisi Teknologi",
        position: "Staff Senior Teknologi",
    },
    {
        id: "STF012",
        name: "Sari Indah",
        email: "stf012@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "MGR002",
        department: "Divisi Teknologi",
        position: "Admin Teknologi",
    },

    // Under AM003
    {
        id: "STF013",
        name: "Teguh Santoso",
        email: "stf013@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM003",
        department: "Tim Infrastruktur IT",
        position: "Network Engineer",
    },
    {
        id: "STF014",
        name: "Uswatun Hasanah",
        email: "stf014@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM003",
        department: "Tim Infrastruktur IT",
        position: "System Administrator",
    },
    {
        id: "STF015",
        name: "Vika Ramadhani",
        email: "stf015@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM003",
        department: "Tim Infrastruktur IT",
        position: "IT Support",
    },
    {
        id: "STF016",
        name: "Wahyu Budiman",
        email: "stf016@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM003",
        department: "Tim Infrastruktur IT",
        position: "IT Support",
    },

    // Under AM004
    {
        id: "STF017",
        name: "Xena Puspita",
        email: "stf017@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM004",
        department: "Tim Pengembangan Sistem",
        position: "Frontend Developer",
    },
    {
        id: "STF018",
        name: "Yudi Prasetyo",
        email: "stf018@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM004",
        department: "Tim Pengembangan Sistem",
        position: "Backend Developer",
    },
    {
        id: "STF019",
        name: "Zara Novita",
        email: "stf019@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM004",
        department: "Tim Pengembangan Sistem",
        position: "QA Engineer",
    },
    {
        id: "STF020",
        name: "Agus Hermawan",
        email: "stf020@company.id",
        password: "password",
        level: 4,
        reporting_to_id: "AM004",
        department: "Tim Pengembangan Sistem",
        position: "DevOps Engineer",
    },
];

// ─────────────────────────────────────────────
// KPIs — cascading hierarchy
// ─────────────────────────────────────────────
export const mockKPIs: KPI[] = [
    // ── VP001 KPIs — KPI Bersama (40%) ──
    {
        id: "KPI-VP001-1",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "EBIT",
        formula: "Laba (Rugi) Usaha + Laba Asosiasi & Ventura Bersama + Laba (Rugi) Selisih Kurs",
        unit: "Rp Miliar",
        weight: 10,
        target: 1565,
        achievement: 1480,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bersama",
    },
    {
        id: "KPI-VP001-2",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Operating Ratio",
        formula: "Biaya Usaha / Pendapatan Usaha",
        unit: "%",
        weight: 10,
        target: 82.66,
        achievement: 84,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "reverse",
        category: "bersama",
    },
    {
        id: "KPI-VP001-3",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Advancing in Sustainable Development Goals",
        formula: "Rata-rata pencapaian Maturity Level Sustainability + Pengelolaan Komunikasi & TJSL",
        unit: "%",
        weight: 10,
        target: 100,
        achievement: 92,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bersama",
    },
    {
        id: "KPI-VP001-4",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Pengembangan Talenta, Produktivitas, HC Services & Safety Culture",
        formula: "Rata-rata: Produktivitas Pegawai + LTIFR + Target Keikutsertaan Lomba Inovasi PLN",
        unit: "%",
        weight: 10,
        target: 100,
        achievement: 95,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bersama",
    },
    {
        id: "KPI-VP001-5",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Compliance",
        formula: "Deduction: GCG + HSSE + SPI/BPK + Keterlambatan Laporan + Corporate Charter + Cyber Security + PACA + Critical Event + NAC",
        unit: "Poin",
        weight: 0,
        target: 0,
        achievement: 2,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "deduction",
        category: "bersama",
        max_deduction: 10,
    },

    // ── VP001 KPIs — KPI Bidang (60%) ──
    {
        id: "KPI-VP001-6",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Smart & Green Building",
        formula: "Jumlah implementasi Smart & Green Building",
        unit: "Gedung",
        weight: 12,
        target: 10,
        achievement: 8,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bidang",
    },
    {
        id: "KPI-VP001-7",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Penyelesaian Solusi Kebutuhan Pelanggan",
        formula: "Jumlah permintaan selesai / jumlah permintaan kebutuhan sales",
        unit: "%",
        weight: 12,
        target: 100,
        achievement: 88,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bidang",
    },
    {
        id: "KPI-VP001-8",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Waktu Penyelesaian Proposal",
        formula: "Rata-rata hari penyelesaian proposal",
        unit: "Hari",
        weight: 12,
        target: 10,
        achievement: 12,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "reverse",
        category: "bidang",
    },
    {
        id: "KPI-VP001-9",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Tingkat Keberhasilan Proposal / Win Rate",
        formula: "Proposal menjadi PO / menang tender",
        unit: "%",
        weight: 12,
        target: 100,
        achievement: 75,
        status: "PendingApproval",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bidang",
    },
    {
        id: "KPI-VP001-10",
        user_id: "VP001",
        parent_kpi_id: null,
        indicator: "Identifikasi Kebutuhan Solusi Bisnis PLN Group",
        formula: "Pekerjaan disetujui PLN Group di luar penugasan DIVSTI",
        unit: "%",
        weight: 12,
        target: 100,
        achievement: 90,
        status: "Approved",
        deadline: "2026-12-31",
        scoring_type: "normal",
        category: "bidang",
    },

    // ── MGR001 KPIs ──
    {
        id: "KPI-MGR001-1",
        user_id: "MGR001",
        parent_kpi_id: "KPI-VP001-6",
        indicator: "Efisiensi Tim Operasional",
        formula: "Rata-rata pencapaian KPI tim operasional",
        unit: "%",
        weight: 40,
        target: 90,
        achievement: 82,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-MGR001-2",
        user_id: "MGR001",
        parent_kpi_id: "KPI-VP001-7",
        indicator: "Kepuasan Pelanggan Layanan & Distribusi",
        formula: "Rata-rata skor survei per kuartal",
        unit: "Skor (1-5)",
        weight: 35,
        target: 4.3,
        achievement: 4.0,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-MGR001-3",
        user_id: "MGR001",
        parent_kpi_id: null,
        indicator: "Penyelesaian Laporan Operasional Tepat Waktu",
        formula: "Jumlah laporan tepat waktu / total laporan x 100%",
        unit: "%",
        weight: 25,
        target: 95,
        achievement: 91,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── MGR002 KPIs ──
    {
        id: "KPI-MGR002-1",
        user_id: "MGR002",
        parent_kpi_id: "KPI-VP001-8",
        indicator: "Ketersediaan Infrastruktur IT Divisi",
        formula: "Uptime sistem divisi / total waktu x 100%",
        unit: "%",
        weight: 40,
        target: 99.5,
        achievement: 99.3,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-MGR002-2",
        user_id: "MGR002",
        parent_kpi_id: "KPI-VP001-9",
        indicator: "Kecepatan Penyelesaian Pengembangan Fitur",
        formula: "Fitur selesai tepat waktu / total fitur x 100%",
        unit: "%",
        weight: 35,
        target: 85,
        achievement: 79,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-MGR002-3",
        user_id: "MGR002",
        parent_kpi_id: null,
        indicator: "Kepatuhan SLA Sistem",
        formula: "Insiden terselesaikan dalam SLA / total insiden x 100%",
        unit: "%",
        weight: 25,
        target: 95,
        achievement: 93,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── AM001 KPIs ──
    {
        id: "KPI-AM001-1",
        user_id: "AM001",
        parent_kpi_id: "KPI-MGR001-1",
        indicator: "Penyelesaian Tiket Layanan Lapangan",
        formula: "Tiket selesai / total tiket x 100%",
        unit: "%",
        weight: 45,
        target: 90,
        achievement: 87,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM001-2",
        user_id: "AM001",
        parent_kpi_id: "KPI-MGR001-2",
        indicator: "First Call Resolution Rate",
        formula: "Masalah selesai di kunjungan pertama / total kunjungan",
        unit: "%",
        weight: 35,
        target: 75,
        achievement: 68,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM001-3",
        user_id: "AM001",
        parent_kpi_id: null,
        indicator: "Waktu Respon Rata-Rata Teknisi",
        formula: "Total waktu respon / jumlah panggilan",
        unit: "Jam",
        weight: 20,
        target: 2,
        achievement: 2.3,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── AM002 KPIs ──
    {
        id: "KPI-AM002-1",
        user_id: "AM002",
        parent_kpi_id: "KPI-MGR001-1",
        indicator: "Ketepatan Jadwal Distribusi",
        formula: "Pengiriman tepat waktu / total pengiriman x 100%",
        unit: "%",
        weight: 50,
        target: 95,
        achievement: 92,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM002-2",
        user_id: "AM002",
        parent_kpi_id: "KPI-MGR001-2",
        indicator: "Akurasi Data Distribusi",
        formula: "Data akurat / total data distribusi x 100%",
        unit: "%",
        weight: 30,
        target: 98,
        achievement: 96,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM002-3",
        user_id: "AM002",
        parent_kpi_id: null,
        indicator: "Efisiensi Rute Pengiriman",
        formula: "Pengurangan jarak tempuh vs bulan lalu",
        unit: "%",
        weight: 20,
        target: 10,
        achievement: 7,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── AM003 KPIs ──
    {
        id: "KPI-AM003-1",
        user_id: "AM003",
        parent_kpi_id: "KPI-MGR002-1",
        indicator: "Uptime Infrastruktur Jaringan",
        formula: "Jam operasi jaringan / total jam x 100%",
        unit: "%",
        weight: 50,
        target: 99.9,
        achievement: 99.7,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM003-2",
        user_id: "AM003",
        parent_kpi_id: "KPI-MGR002-3",
        indicator: "Penyelesaian Insiden Jaringan",
        formula: "Insiden terselesaikan / total insiden x 100%",
        unit: "%",
        weight: 30,
        target: 95,
        achievement: 97,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM003-3",
        user_id: "AM003",
        parent_kpi_id: null,
        indicator: "Pembaruan Patch Keamanan",
        formula: "Server ter-patch / total server x 100%",
        unit: "%",
        weight: 20,
        target: 100,
        achievement: 95,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── AM004 KPIs ──
    {
        id: "KPI-AM004-1",
        user_id: "AM004",
        parent_kpi_id: "KPI-MGR002-2",
        indicator: "Sprint Velocity Tim Pengembang",
        formula: "Story points selesai / sprint",
        unit: "Story Points",
        weight: 40,
        target: 40,
        achievement: 35,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM004-2",
        user_id: "AM004",
        parent_kpi_id: "KPI-MGR002-3",
        indicator: "Bug Rate Pasca Rilis",
        formula: "Bug kritis ditemukan / fitur dirilis",
        unit: "Bug/Fitur",
        weight: 35,
        target: 0.5,
        achievement: 0.8,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-AM004-3",
        user_id: "AM004",
        parent_kpi_id: null,
        indicator: "Code Coverage Automated Tests",
        formula: "Baris kode tercakup unit test / total baris",
        unit: "%",
        weight: 25,
        target: 80,
        achievement: 72,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // ── Staff KPIs ──
    // STF001 (under MGR001)
    {
        id: "KPI-STF001-1",
        user_id: "STF001",
        parent_kpi_id: "KPI-MGR001-3",
        indicator: "Penyelesaian Laporan Harian",
        formula: "Laporan selesai tepat waktu / total laporan",
        unit: "%",
        weight: 60,
        target: 100,
        achievement: 95,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF001-2",
        user_id: "STF001",
        parent_kpi_id: null,
        indicator: "Kehadiran & Disiplin Kerja",
        formula: "Hari hadir / hari kerja x 100%",
        unit: "%",
        weight: 40,
        target: 98,
        achievement: 100,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF002 (under MGR001)
    {
        id: "KPI-STF002-1",
        user_id: "STF002",
        parent_kpi_id: "KPI-MGR001-3",
        indicator: "Akurasi Input Data Administrasi",
        formula: "Data benar / total data diinputkan x 100%",
        unit: "%",
        weight: 70,
        target: 99,
        achievement: 97,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF002-2",
        user_id: "STF002",
        parent_kpi_id: null,
        indicator: "Kehadiran & Disiplin Kerja",
        formula: "Hari hadir / hari kerja x 100%",
        unit: "%",
        weight: 30,
        target: 98,
        achievement: 96,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF003 (under AM001)
    {
        id: "KPI-STF003-1",
        user_id: "STF003",
        parent_kpi_id: "KPI-AM001-1",
        indicator: "Jumlah Tiket Diselesaikan",
        formula: "Total tiket selesai per bulan",
        unit: "Tiket",
        weight: 50,
        target: 30,
        achievement: 28,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF003-2",
        user_id: "STF003",
        parent_kpi_id: "KPI-AM001-2",
        indicator: "Kepuasan Pelanggan per Teknisi",
        formula: "Rata-rata rating pelanggan",
        unit: "Skor (1-5)",
        weight: 50,
        target: 4.5,
        achievement: 4.3,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF004 (under AM001)
    {
        id: "KPI-STF004-1",
        user_id: "STF004",
        parent_kpi_id: "KPI-AM001-1",
        indicator: "Jumlah Tiket Diselesaikan",
        formula: "Total tiket selesai per bulan",
        unit: "Tiket",
        weight: 60,
        target: 30,
        achievement: 25,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF004-2",
        user_id: "STF004",
        parent_kpi_id: null,
        indicator: "Pemeliharaan Peralatan Lapangan",
        formula: "Peralatan terpelihara / total peralatan x 100%",
        unit: "%",
        weight: 40,
        target: 100,
        achievement: 90,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF005 (under AM001)
    {
        id: "KPI-STF005-1",
        user_id: "STF005",
        parent_kpi_id: "KPI-AM001-3",
        indicator: "Waktu Respon Panggilan Darurat",
        formula: "Rata-rata waktu dari panggilan ke lokasi",
        unit: "Jam",
        weight: 60,
        target: 1.5,
        achievement: 1.8,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF005-2",
        user_id: "STF005",
        parent_kpi_id: null,
        indicator: "Pelatihan & Kompetensi",
        formula: "Jumlah sertifikasi diperoleh / target",
        unit: "Sertifikasi",
        weight: 40,
        target: 2,
        achievement: 2,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF006 (under AM001)
    {
        id: "KPI-STF006-1",
        user_id: "STF006",
        parent_kpi_id: "KPI-AM001-1",
        indicator: "Jumlah Tiket Diselesaikan",
        formula: "Total tiket selesai per bulan",
        unit: "Tiket",
        weight: 70,
        target: 25,
        achievement: 22,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF006-2",
        user_id: "STF006",
        parent_kpi_id: null,
        indicator: "Laporan Kunjungan Harian",
        formula: "Laporan diisi / total hari kerja x 100%",
        unit: "%",
        weight: 30,
        target: 100,
        achievement: 98,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF007 (under AM002)
    {
        id: "KPI-STF007-1",
        user_id: "STF007",
        parent_kpi_id: "KPI-AM002-1",
        indicator: "Koordinasi Pengiriman Tepat Waktu",
        formula: "Pengiriman dikoordinasi tepat waktu / total",
        unit: "%",
        weight: 60,
        target: 95,
        achievement: 93,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF007-2",
        user_id: "STF007",
        parent_kpi_id: null,
        indicator: "Pemantauan Status Pengiriman",
        formula: "Update status / total pengiriman x 100%",
        unit: "%",
        weight: 40,
        target: 100,
        achievement: 99,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF008 (under AM002)
    {
        id: "KPI-STF008-1",
        user_id: "STF008",
        parent_kpi_id: "KPI-AM002-2",
        indicator: "Akurasi Data Pengiriman",
        formula: "Data benar per manifes / total data",
        unit: "%",
        weight: 70,
        target: 99,
        achievement: 98,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF008-2",
        user_id: "STF008",
        parent_kpi_id: null,
        indicator: "Kehadiran & Disiplin",
        formula: "Hari hadir / hari kerja x 100%",
        unit: "%",
        weight: 30,
        target: 98,
        achievement: 97,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF009 (under AM002)
    {
        id: "KPI-STF009-1",
        user_id: "STF009",
        parent_kpi_id: "KPI-AM002-1",
        indicator: "Volume Pengiriman Diproses",
        formula: "Total unit pengiriman diproses per bulan",
        unit: "Unit",
        weight: 60,
        target: 500,
        achievement: 463,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF009-2",
        user_id: "STF009",
        parent_kpi_id: null,
        indicator: "Pelaporan Anomali Pengiriman",
        formula: "Anomali dilaporkan / total anomali temukan x 100%",
        unit: "%",
        weight: 40,
        target: 100,
        achievement: 88,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF010 (under AM002)
    {
        id: "KPI-STF010-1",
        user_id: "STF010",
        parent_kpi_id: "KPI-AM002-2",
        indicator: "Ketepatan Entri Data Logistik",
        formula: "Entri benar / total entri x 100%",
        unit: "%",
        weight: 60,
        target: 99,
        achievement: 95,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF010-2",
        user_id: "STF010",
        parent_kpi_id: null,
        indicator: "Penyelesaian Rekonsiliasi Bulanan",
        formula: "Rekonsiliasi selesai tepat waktu / total x 100%",
        unit: "%",
        weight: 40,
        target: 100,
        achievement: 100,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF011 (under MGR002)
    {
        id: "KPI-STF011-1",
        user_id: "STF011",
        parent_kpi_id: "KPI-MGR002-1",
        indicator: "Pemeliharaan Server Produksi",
        formula: "Server dijaga uptime / total server x 100%",
        unit: "%",
        weight: 60,
        target: 99.5,
        achievement: 99.8,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF011-2",
        user_id: "STF011",
        parent_kpi_id: null,
        indicator: "Dokumentasi Teknis",
        formula: "Dokumen teknis dibuat / target per kuartal",
        unit: "Dokumen",
        weight: 40,
        target: 5,
        achievement: 4,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF012 (under MGR002)
    {
        id: "KPI-STF012-1",
        user_id: "STF012",
        parent_kpi_id: "KPI-MGR002-3",
        indicator: "Pengelolaan Tiket Teknologi",
        formula: "Tiket selesai / total tiket x 100%",
        unit: "%",
        weight: 70,
        target: 95,
        achievement: 91,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF012-2",
        user_id: "STF012",
        parent_kpi_id: null,
        indicator: "Administrasi Aset IT",
        formula: "Aset telah diinventarisir / total aset x 100%",
        unit: "%",
        weight: 30,
        target: 100,
        achievement: 95,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF013 (under AM003)
    {
        id: "KPI-STF013-1",
        user_id: "STF013",
        parent_kpi_id: "KPI-AM003-1",
        indicator: "Uptime Jaringan WAN/LAN",
        formula: "Jam jaringan up / total jam x 100%",
        unit: "%",
        weight: 70,
        target: 99.9,
        achievement: 99.8,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF013-2",
        user_id: "STF013",
        parent_kpi_id: null,
        indicator: "Penanganan Insiden Jaringan",
        formula: "Insiden ditangani / total insiden x 100%",
        unit: "%",
        weight: 30,
        target: 95,
        achievement: 97,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF014 (under AM003)
    {
        id: "KPI-STF014-1",
        user_id: "STF014",
        parent_kpi_id: "KPI-AM003-1",
        indicator: "Ketersediaan Server Aplikasi",
        formula: "Server up / total server x 100%",
        unit: "%",
        weight: 60,
        target: 99.5,
        achievement: 99.9,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF014-2",
        user_id: "STF014",
        parent_kpi_id: "KPI-AM003-3",
        indicator: "Implementasi Patch Keamanan",
        formula: "Patch diimplementasikan / total patch tersedia",
        unit: "%",
        weight: 40,
        target: 100,
        achievement: 95,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF015 (under AM003)
    {
        id: "KPI-STF015-1",
        user_id: "STF015",
        parent_kpi_id: "KPI-AM003-2",
        indicator: "Penyelesaian Tiket IT Support",
        formula: "Tiket selesai / total tiket x 100%",
        unit: "%",
        weight: 60,
        target: 95,
        achievement: 96,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF015-2",
        user_id: "STF015",
        parent_kpi_id: null,
        indicator: "First Level Resolution",
        formula: "Masalah selesai tanpa eskalasi / total masalah",
        unit: "%",
        weight: 40,
        target: 80,
        achievement: 77,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF016 (under AM003)
    {
        id: "KPI-STF016-1",
        user_id: "STF016",
        parent_kpi_id: "KPI-AM003-2",
        indicator: "Penyelesaian Tiket IT Support",
        formula: "Tiket selesai / total tiket x 100%",
        unit: "%",
        weight: 70,
        target: 95,
        achievement: 94,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF016-2",
        user_id: "STF016",
        parent_kpi_id: null,
        indicator: "Kepuasan User IT Support",
        formula: "Rata-rata rating dari user setelah tiket selesai",
        unit: "Skor (1-5)",
        weight: 30,
        target: 4.5,
        achievement: 4.2,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF017 (under AM004)
    {
        id: "KPI-STF017-1",
        user_id: "STF017",
        parent_kpi_id: "KPI-AM004-1",
        indicator: "Story Points Diselesaikan",
        formula: "Total story points per sprint",
        unit: "Story Points",
        weight: 60,
        target: 20,
        achievement: 18,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF017-2",
        user_id: "STF017",
        parent_kpi_id: "KPI-AM004-3",
        indicator: "Unit Test Coverage Frontend",
        formula: "Baris frontend tercakup / total baris x 100%",
        unit: "%",
        weight: 40,
        target: 80,
        achievement: 72,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF018 (under AM004)
    {
        id: "KPI-STF018-1",
        user_id: "STF018",
        parent_kpi_id: "KPI-AM004-1",
        indicator: "Story Points Diselesaikan",
        formula: "Total story points per sprint",
        unit: "Story Points",
        weight: 50,
        target: 25,
        achievement: 22,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF018-2",
        user_id: "STF018",
        parent_kpi_id: "KPI-AM004-2",
        indicator: "Bug Rate API yang Dikembangkan",
        formula: "Bug kritis API / total endpoint dirilis",
        unit: "Bug/Endpoint",
        weight: 50,
        target: 0.3,
        achievement: 0.5,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF019 (under AM004)
    {
        id: "KPI-STF019-1",
        user_id: "STF019",
        parent_kpi_id: "KPI-AM004-2",
        indicator: "Test Case Execution Rate",
        formula: "Test case dieksekusi / total test case x 100%",
        unit: "%",
        weight: 60,
        target: 100,
        achievement: 95,
        status: "PendingApproval",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF019-2",
        user_id: "STF019",
        parent_kpi_id: null,
        indicator: "Defect Detection Rate",
        formula: "Bug ditemukan QA / total bug terkonfirmasi",
        unit: "%",
        weight: 40,
        target: 90,
        achievement: 85,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },

    // STF020 (under AM004)
    {
        id: "KPI-STF020-1",
        user_id: "STF020",
        parent_kpi_id: "KPI-AM004-3",
        indicator: "CI/CD Pipeline Success Rate",
        formula: "Pipeline berhasil / total pipeline dijalankan",
        unit: "%",
        weight: 60,
        target: 95,
        achievement: 92,
        status: "Approved",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
    {
        id: "KPI-STF020-2",
        user_id: "STF020",
        parent_kpi_id: null,
        indicator: "Deployment Frequency",
        formula: "Jumlah deployment ke production per bulan",
        unit: "Deployment",
        weight: 40,
        target: 12,
        achievement: 10,
        status: "Draft",
        deadline: "2025-12-31",
        scoring_type: "normal",
        category: null,
    },
];

// ─────────────────────────────────────────────
// ALERTS
// ─────────────────────────────────────────────
export const mockAlerts: Alert[] = [
    {
        id: "ALT-001",
        user_id: "VP001",
        type: "Approval",
        message: "MGR001 mengajukan KPI 'Penyelesaian Laporan Operasional Tepat Waktu' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-01T10:00:00Z",
        related_kpi_id: "KPI-MGR001-3",
    },
    {
        id: "ALT-002",
        user_id: "VP001",
        type: "Approval",
        message: "MGR002 mengajukan KPI 'Kepatuhan SLA Sistem' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-01T11:00:00Z",
        related_kpi_id: "KPI-MGR002-3",
    },
    {
        id: "ALT-003",
        user_id: "VP001",
        type: "MissedTarget",
        message: "KPI 'Indeks Kepuasan Pelanggan (IKP)' masih di 93.3% dari target. Perlu perhatian.",
        is_read: true,
        created_at: "2025-11-15T09:00:00Z",
    },
    {
        id: "ALT-004",
        user_id: "MGR001",
        type: "Approval",
        message: "AM001 mengajukan KPI 'Waktu Respon Rata-Rata Teknisi' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-02T08:00:00Z",
        related_kpi_id: "KPI-AM001-3",
    },
    {
        id: "ALT-005",
        user_id: "MGR001",
        type: "Approval",
        message: "STF002 mengajukan KPI 'Akurasi Input Data Administrasi' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-02T09:00:00Z",
        related_kpi_id: "KPI-STF002-1",
    },
    {
        id: "ALT-006",
        user_id: "MGR001",
        type: "MissedTarget",
        message: "AM001: 'First Call Resolution Rate' hanya mencapai 68% dari target 75%.",
        is_read: true,
        created_at: "2025-11-20T14:00:00Z",
    },
    {
        id: "ALT-007",
        user_id: "MGR002",
        type: "Approval",
        message: "AM003 mengajukan KPI 'Pembaruan Patch Keamanan' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-03T10:00:00Z",
        related_kpi_id: "KPI-AM003-3",
    },
    {
        id: "ALT-008",
        user_id: "MGR002",
        type: "MissedTarget",
        message: "AM004: 'Bug Rate Pasca Rilis' melebihi target (0.8 vs target 0.5).",
        is_read: false,
        created_at: "2025-12-01T16:00:00Z",
    },
    {
        id: "ALT-009",
        user_id: "AM001",
        type: "Approval",
        message: "STF003 mengajukan KPI 'Jumlah Tiket Diselesaikan' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-04T08:00:00Z",
        related_kpi_id: "KPI-STF003-1",
    },
    {
        id: "ALT-010",
        user_id: "AM001",
        type: "Approval",
        message: "STF005 mengajukan KPI 'Waktu Respon Panggilan Darurat' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-04T09:00:00Z",
        related_kpi_id: "KPI-STF005-1",
    },
    {
        id: "ALT-011",
        user_id: "AM001",
        type: "Deadline",
        message: "KPI 'First Call Resolution Rate' mendekati deadline (31 Desember). Segera isi capaian.",
        is_read: false,
        created_at: "2025-12-10T07:00:00Z",
    },
    {
        id: "ALT-012",
        user_id: "AM002",
        type: "Approval",
        message: "STF008 mengajukan KPI 'Akurasi Data Pengiriman' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-05T08:00:00Z",
        related_kpi_id: "KPI-STF008-1",
    },
    {
        id: "ALT-013",
        user_id: "AM002",
        type: "Approval",
        message: "STF010 mengajukan KPI 'Ketepatan Entri Data Logistik' untuk persetujuan.",
        is_read: true,
        created_at: "2025-12-05T09:00:00Z",
        related_kpi_id: "KPI-STF010-1",
    },
    {
        id: "ALT-014",
        user_id: "AM003",
        type: "Approval",
        message: "STF014 mengajukan KPI 'Implementasi Patch Keamanan' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-06T08:00:00Z",
        related_kpi_id: "KPI-STF014-2",
    },
    {
        id: "ALT-015",
        user_id: "AM003",
        type: "Approval",
        message: "STF016 mengajukan KPI 'Penyelesaian Tiket IT Support' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-06T09:00:00Z",
        related_kpi_id: "KPI-STF016-1",
    },
    {
        id: "ALT-016",
        user_id: "AM004",
        type: "Approval",
        message: "STF018 mengajukan KPI 'Story Points Diselesaikan' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-07T08:00:00Z",
        related_kpi_id: "KPI-STF018-1",
    },
    {
        id: "ALT-017",
        user_id: "AM004",
        type: "Approval",
        message: "STF019 mengajukan KPI 'Test Case Execution Rate' untuk persetujuan.",
        is_read: false,
        created_at: "2025-12-07T09:00:00Z",
        related_kpi_id: "KPI-STF019-1",
    },
    {
        id: "ALT-018",
        user_id: "AM004",
        type: "MissedTarget",
        message: "KPI 'Bug Rate Pasca Rilis' sudah melebihi batas target. Perlu tindakan korektif.",
        is_read: true,
        created_at: "2025-12-01T15:00:00Z",
    },
    {
        id: "ALT-019",
        user_id: "STF003",
        type: "Changed",
        message: "KPI induk 'Penyelesaian Tiket Layanan Lapangan' (AM001) telah diperbarui targetnya.",
        is_read: false,
        created_at: "2025-12-02T10:00:00Z",
    },
    {
        id: "ALT-020",
        user_id: "STF005",
        type: "MissedTarget",
        message: "KPI 'Waktu Respon Panggilan Darurat' melebihi target (1.8 jam vs target 1.5 jam).",
        is_read: false,
        created_at: "2025-12-05T14:00:00Z",
    },
    {
        id: "ALT-021",
        user_id: "STF018",
        type: "MissedTarget",
        message: "KPI 'Bug Rate API' melebihi target (0.5 vs target 0.3). Perlu review kode.",
        is_read: false,
        created_at: "2025-12-04T16:00:00Z",
    },
    {
        id: "ALT-022",
        user_id: "STF011",
        type: "Approval",
        message: "KPI 'Dokumentasi Teknis' sudah diajukan. Menunggu persetujuan MGR002.",
        is_read: true,
        created_at: "2025-12-08T08:00:00Z",
    },
    {
        id: "ALT-023",
        user_id: "MGR001",
        type: "Deadline",
        message: "Deadline pengisian KPI 'Penyelesaian Laporan Operasional Tepat Waktu' tinggal 3 minggu.",
        is_read: false,
        created_at: "2025-12-10T07:00:00Z",
    },
    {
        id: "ALT-024",
        user_id: "STF002",
        type: "Changed",
        message: "KPI 'Akurasi Input Data Administrasi' Anda telah diperbarui oleh MGR001.",
        is_read: false,
        created_at: "2025-12-09T11:00:00Z",
    },
];

// ─────────────────────────────────────────────
// SYSTEM CONFIGS
// ─────────────────────────────────────────────
export const mockConfigs: SystemConfig[] = [
    {
        key: "app_timezone",
        value: "Asia/Jakarta",
        description: "Zona waktu default sistem",
        updated_at: new Date().toISOString()
    },
    {
        key: "maintenance_mode",
        value: "false",
        description: "Mode pemeliharaan aplikasi (true/false)",
        updated_at: new Date().toISOString()
    },
    {
        key: "active_kpi_period",
        value: "2026",
        description: "Periode tahun aktif untuk pengisian KPI saat ini",
        updated_at: new Date().toISOString()
    },
    {
        key: "kpi_lock_date",
        value: "2026-12-31T23:59:59.000Z",
        description: "Batas waktu pengisian KPI sebelum terkunci otomatis",
        updated_at: new Date().toISOString()
    }
];
